# Generated by Django 3.2.4 on 2021-06-21 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name you would like to give to your journal.', max_length=50, verbose_name='Name of Journal')),
                ('description', models.TextField(blank=True, help_text='What is this journal about?', max_length=100, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('background_color', models.CharField(help_text='Color to give to the background of the journal', max_length=10)),
                ('text_color', models.CharField(help_text='color to give the text', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Pour out your heart here')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal.journal')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
