# Generated by Django 3.2.4 on 2021-06-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20210621_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='background_color',
            field=models.CharField(help_text='Color to give to the background of the journal', max_length=10, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='text_color',
            field=models.CharField(help_text='color to give the text', max_length=10, verbose_name='Text Color'),
        ),
    ]
