# Generated by Django 3.2.4 on 2021-06-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
