# Generated by Django 3.2.4 on 2021-06-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_journal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
