# Generated by Django 3.2.4 on 2021-06-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_journal_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
